export const manufacturers = [
 "Alfa Romeo",
"Aston Martin",
"Audi",
"Bentley",
"BMW",
"Buick",
"Cadillac",
"Chevrolet",
"Chrysler",
"Citroën",
"Dacia",
"Dodge",
"Ferrari",
"Fiat",
"Ford",
"GAC",
"Genesis",
"GMC",
"Honda",
"Hyundai",
"Infiniti",
"Isuzu",
"Jaguar",
"Jeep",
"Kia",
"Lamborghini",
"Land Rover",
"Lexus",
"Lincoln",
"Lotus",
"Maserati",
"Mazda",
"McLaren",
"Mercedes-Benz",
"MINI",
"Mitsubishi",
"Nissan",
"Opel",
"Peugeot",
"Porsche",
"Ram",
"Renault",
"Rolls-Royce",
"SEAT",
"Škoda",
"Smart",
"Subaru",
"Suzuki",
"Tesla",
"Toyota",
"Volkswagen",
"Volvo",
"XPeng",
"BYD",
"Chery",
"Geely",
"MG",
"Lynk & Co",
"Great Wall",
"Jaecoo",
"TANK",
"Voyah",
"ZEEKR",
"Citroën DS",
"DS Automobiles"

];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2024", value: "2024" },
  { title: "2023", value: "2023" },
  { title: "2022", value: "2022" },
  { title: "2021", value: "2021" },
  { title: "2020", value: "2020" },
  { title: "2019", value: "2019" },
  { title: "2018", value: "2018" },
  { title: "2017", value: "2017" },
  { title: "2016", value: "2016" },
  { title: "2015", value: "2015" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
   {
      title: "Hybrid",
      value: "hHbrid",
    },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
